spring:
  cloud:
    nacos:
      discovery:
        server-addr:  123123
    alicloud:
      sms:
        host:
        path:
        smsSignId:
        templateId:
        appcode:
  application:
    name: gulimall-third-party
server:
  port: 30000