spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQQJkcPjKxhiW4LcFAm
      secret-key: cZwV6sZMdaX8qQtRItkTAtjdDeidFu
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-zhouhr
  application:
    name: gulimall-third-party
server:
  port: 30000